server:
  port: 8002
spring:
  application:
    name: lovegou-product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lovegou_product
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka  #告诉服务提供者要把服务注册到哪儿 #单机环境
  instance:
    prefer-ip-address: true
mybatis-plus:
   mapper-locations: classpath:io/itsource/lx/lovegou/mapper/*Mapper.xml
#  type-aliases-package: